spring:
  application:
    name: FilthiBlog

jwt:
  secret: ${JWT_SECRET:MeH8FsvNvyR3Jp/NpcHvusWIXleHlGR+ZM6dI+jLIvRvvS4DiKTwM/RKJxkL+pdj0vx+owOQMZDrcQyJK+pKLw==}
  expiration: ${JWT_EXPIRATION:86400000}
