spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update        # only in local dev â€“ makes iteration fast

  flyway:
    enabled: false           # let Hibernate handle schema locally